### ISSUE TITLE
update : FeedScreen

### ISSUE THREAD

**Issue by wooongyee** [capstone-3-team/android#25]
## Todo

* [x] 복습 완료 버튼 구현 및 카드 리스트 정렬
* [x] Card Component Markdown으로 변경
* [ ] 해시태그 최대 3줄까지
* [x] 제목 길어졌을 때 eclipse 적용
